BEGIN TRANSACTION;

ALTER TABLE Books
ADD FOREIGN KEY (authorID) REFERENCES Authors(authorID);

ALTER TABLE Orders
ADD FOREIGN KEY (bookID) REFERENCES Books(bookID);

ALTER TABLE Reviews
ADD FOREIGN KEY (reviewerID) REFERENCES Members(memberID);

COMMIT;
